### ISSUE TITLE
API get user

### ISSUE THREAD

**Issue by chrisvidal** [rluders/oc-jwtauth-plugin#1]
Hi
I am doing some testing using the Postman collection.
I managed to login. 
When I am trying to get the user with `/api/auth/me` in postman I  got an exception, even if I set the header as documented (Authorization and Bearer **token**)

```
<p class="lead">We're sorry, but an unhandled error occurred. Please see the details below.</p>
            <div class="exception-name-block">
                <div>Token not provided</div>
                <p>/Users/christophevidal/Sites/oc-vodka/plugins/rluders/jwtauth/vendor/tymon/jwt-auth/src/Http/Middleware/BaseMiddleware.php 
                    <span>line</span> 52
                </p>
```

**Comment by rluders** [comment]
Hey @chrisvidal 

![image](https://user-images.githubusercontent.com/191027/45685151-b7c54b80-bb48-11e8-81e4-00c2203c72d4.png)

Are you replacing the `put-yout-jwt-token-here` (ops, typo) by your user auth token?

Can you provide me more informations about the steps that you are following? Something to reproduce the error, like:

1. Login
2. Get user auth token
3. ....  

Thanks.

**Comment by chrisvidal** [comment]
Thanks for your answer
Yes I do a simple login with email then copy/paste the token within the Get User request

Login
<img width="949" alt="screenshot 2018-09-18 22 03 45" src="https://user-images.githubusercontent.com/2263496/45693152-0bf31e80-bb8f-11e8-9dcd-dab523c0ef15.png">

Get user
<img width="1058" alt="screenshot 2018-09-18 22 04 39" src="https://user-images.githubusercontent.com/2263496/45693181-19100d80-bb8f-11e8-8217-31e7d8acb607.png">


thanks for your help

**Comment by rluders** [comment]
@chrisvidal amazing details. Thank you, I'll check what is happening.

**Comment by chrisvidal** [comment]
Did you manage to explore the problem on your side?

**Comment by rluders** [comment]
Hey, @chrisvidal 

Not yet, but I'll probably do it during the weekend.

**Comment by chrisvidal** [comment]
any updates on your side? Did you manage to have look?

thanks

**Comment by rluders** [comment]
@chrisvidal Not yet. I was unable to simulate the issue, so far. But, since I was in vacation last week, I don't had the time to dig on it. Right now, I'm setting up an new and clean enviorement to trying to reproduce the issue on an new installation.

**Comment by rluders** [comment]
Issue confirmed.

**Comment by rluders** [comment]
@chrisvidal the issue related to the `/me` endpoint is now fixed. We still having the issue with the `/refresh-token` endpoint.

**Comment by chrisvidal** [comment]
that's awesome! Let me refresh the plugin through OC backend and test.
Thanks

**Comment by jeffreygu** [comment]
Hi @chrisvidal and @rluders  , do you get the bug fixed with new release 1.2.3?  I still can get the issue with same steps as you. I checked the patch, it seems the changes are not be triggered between user login and call /me endpoint.

**Comment by rluders** [comment]
@jeffreygu It was working for me, but maybe I missed something. I'm accepting pull requests to fix this issue.

**Comment by jeffreygu** [comment]
Hi @rluders , it's a apache server configuration issue, which is mentioned in https://github.com/tymondesigns/jwt-auth/wiki/Authentication. It works after I add below config items in .htaccess.


**RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]**

**Comment by rluders** [comment]
@jeffreygu great, good to know, maybe we need to add this information to README.md. If you want to do that, I'll accept your pull request.
