### ISSUE TITLE
The token could not be parsed from the request

### ISSUE THREAD

**Issue by jacksun101** [rluders/oc-jwtauth-plugin#19]
I got an error like this. The RewriteRule is added in the .htaccess. 

`<div>The token could not be parsed from the request</div>
                <p><....>/plugins/rluders/jwtauth/vendor/tymon/jwt-auth/src/JWT.php 
                    <span>line</span> 185
                </p>`

Any idea?

**Comment by rluders** [comment]
Hi Jack.

Not really. Can you provide more info, such as PHP Verison, October version, etc?

Thank you.

**Comment by jacksun101** [comment]
@rluders Sorry, it turns out that the user was not activated. After the activation, the login api runs well.

**Comment by rluders** [comment]
@jacksun101 No problem at all... ;)
