### ISSUE TITLE
Carbon Error on Plugin Installation

### ISSUE THREAD

**Issue by danielbruni** [rluders/oc-jwtauth-plugin#22]
Iam getting the following Error on a fresh October Installation with Apache and PHP 7.1 and 7.2:

> Declaration of Jenssegers\Date\Date::add($interval) must be compatible with Carbon\CarbonInterface::add($unit, $value = 1, $overflow = NULL)

**Comment by rluders** [comment]
That's is weird, but... Do not seems to be related to my plugin. I don't
remember to use this dependency.

Can you provide more details about your installation?

**Comment by danielbruni** [comment]
Thanks for the quick reply. Just made a new Octobercms install on my server and was trying to install your plugin (no other plugins installed) and during the installation process this error shows up.

There is a nesbot/carbon in your plugins vendors folder. Iam using OctoberCMS 448.

**Comment by rluders** [comment]
Ok. I'll check it out when I get home.

**Comment by rluders** [comment]
Looks like we have two packages colliding. The first one is installed by the OctoberCMS Library and the second one is being installed by the 'tymon/jwt-auth', causing an conflict between two Carbon versions.

At this point I have no idea how to solve it. I need to investigate.

**Comment by rluders** [comment]
Just adding one more extra information... Looks like the real issue is related to 'jenssegers/date' that is using an outdated Carbon version. So, I was looking the repository and it seems a little bit abandoned for me... in this case, I'll try to submit a PR to update it's dependencies.

**Comment by rluders** [comment]
OK. I'll try something else during this week, my initial aproach seems to be more complicated. So, it was working before, maybe I just need to 'downgrade' a version of the `tymon/jwt-auth` library that I'm using.

**Comment by rluders** [comment]
**Just one workarround that could help for now:**

The issue only ocurres if you run OctoberCMS over PHP 7.1+, so, if you downgrade your PHP to 7.0 it should be fine. It's not a solution, it's just an workarround while I'm working to fix it.

**Comment by sandyandi** [comment]
@rluders can you please create a version of your plugin that use tymon/jwt-auth version 1.0.0-rc.3 instead of the latest version (1.0.0-rc.4)? rc3 doesn't have Carbon 2.

It makes sense to do so as your plugin is made for October CMS which doesn't support Carbon 2 yet.

**Comment by rluders** [comment]
Actually, I'm doing this. Just need to test it before release.

**Comment by rluders** [comment]
I posted today a patch, that downgrade the `tymon/jwt-auth` library to avoid the issues with Carbon. In my tests it worked fine (but, since I don't have unit tests for this plugin yet), if someone find something wrong, please, let me know.

**It is possible that you need to remove the plugin and install it again.**
