### ISSUE TITLE
How to create a custom login request?

### ISSUE THREAD

**Issue by jacksun101** [rluders/oc-jwtauth-plugin#23]
Sorry, this is not an issue, but a question. 

I would like to create a custom login for jwt. The custom login would be using an unique uuid code of device which belongs to an user. No password, just an uuid login request, if exists then dispatch a token. Is there any best practice for this idea? 

Thanks.

**Comment by rluders** [comment]
In this case, I think that is better for you to read about [OAuth2](https://oauth.net/2/) protocol.
