### ISSUE TITLE
Invalid response Content-Type when username has already been taken.

### ISSUE THREAD

**Issue by paishin** [rluders/oc-jwtauth-plugin#38]
I am facing a very strange issue where when a username has already been taken the response I get is in html instead of text/json. If the email has been taken then the response is in text/json.

Also I have found out that this depends on the primary login method of the 'Users Plugin'; if set to username then username taken returns text/json and email returns text/html.

![image](https://user-images.githubusercontent.com/410381/94878488-3e1a0500-0466-11eb-8b5d-fdf08c42f1df.png)

![image](https://user-images.githubusercontent.com/410381/94878560-715c9400-0466-11eb-93a7-a79ee9cd6f22.png)

**Comment by DavidSota-ABDD** [comment]
@paishin I, too, had noticed this in a project we've been developing; I simply did not have the time to report it. Thank you for this!

I can, however, add that this also seems to happen when a **token expires** or is **blacklisted**.

**Comment by rluders** [comment]
Interesting. If someone had time to fix it, I'll accept the PR.
Otherwise, I can fix it in +2 weeks. Really busy time for me right now.

**Comment by rluders** [comment]
It should be fixed right now.
