### ISSUE TITLE
French translation ?

### ISSUE THREAD

**Issue by Incremental92** [rluders/oc-jwtauth-plugin#50]
Ahoj, if you don't have a french translation, I can provide one ?

**Comment by rluders** [comment]
Only if someone speaks French send me a PR. Let ask for help. :)

**Comment by Incremental92** [comment]
I'm french, so I can help.

**Comment by rluders** [comment]
So, just create a PR adding the `fr` translation. 

https://github.com/rluders/oc-jwtauth-plugin/tree/main/lang

**Comment by Incremental92** [comment]
Hi, not sure I've done it well for a first time....

**Comment by Incremental92** [comment]
Hello, please could you confirm that you found my file ?
I was not able to create the PR

**Comment by rluders** [comment]
@Incremental92 I was checking ur fork, and there are no changes over there. I'll recommend you this tutorial: https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

**Comment by Incremental92** [comment]
Thanks, it should work now.

**Comment by Incremental92** [comment]
Corrections made.

**Comment by rluders** [comment]
I'll validate it during the weekend. Thank you!
