### ISSUE TITLE
Install error "Method subMinutes does not exist." 

### ISSUE THREAD

**Issue by mlieshout** [rluders/oc-jwtauth-plugin#53]
Hi,

I'm trying to install the plugin from the October CMS Marketplace and get this error:

"Method subMinutes does not exist." on line 96 of  .../vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php

- OctoberCMS Build: 471
- PHP Version: 7.4.12

**Comment by rluders** [comment]
Hello, @mlieshout.

Thank you for reporting the issue. Sorry about it. Let me run some tests, and validate the issue.

**Comment by rluders** [comment]
It seems that when I updated the plugin dependencies it overwrites some related dependencies, which is causing some conflicts with the ones that belong to OctoberCMS.

I'm planning to patch this issue this weekend. I let you know about it ASAP. Sorry about it.

It only reinforces what I was thinking a few weeks ago, that I need to spend some time adding some automated tests to the plugin.

**Comment by mlieshout** [comment]
Hi Ricardo,

Thanks for the update on this issue!
I don't need it asap so please take your time to do what you have to do.

**Comment by rluders** [comment]
@mlieshout I just did a small fix. Can you try it and let me know? Thank you.

**Comment by mlieshout** [comment]
This is what I did:

Added the composer.json to the plugin directory and ran "composer update"
Now I get this error:

"Method addSeconds does not exist."
in vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php line
96

Op vr 22 jan. 2021 om 14:53 schreef Ricardo Lüders <notifications@github.com

**Comment by rluders** [comment]
Ok. Thank you.

I don't know what is happening, I did the fix, it was working, then tried to install it again, and it seems that it is still broken.

I'll spend more time during the weekend. Doesn't seems to be something that simple to fix.

**Comment by rluders** [comment]
Just release the patch. It is working on 470, that is/or should be the same as the 471 [release note](https://octobercms.com/support/article/cl-470)

If you still having issues with 471, I do recommend you check the try to get "back" to 470 by reinstalling the OctoberCMS. I'm installing it using the composer ([guide here](https://octobercms.com/docs/console/commands#console-install-composer)) and it is working like a charm.

Also, I do recommend you reinstall the JWTAuth Plugin, just to make sure that everything is clean and shiny. :sun_with_face: 

Please, let me know if you have any other issues.

**Comment by rluders** [comment]
I reported it to the OctoberCMS team, it seems to be an issue related to Marketplace itself. I'll keep following its progress.

**Comment by rluders** [comment]
All right. This is pretty similar to the issue that is also happening with my CORS plugin. So, you can find some better explanation [here](https://github.com/rluders/oc-cors-plugin/issues/5#issuecomment-770177264), but long story, short.

OctoberCMS has now 2 possible Laravel versions: 5.5 and 6. That is causing issues. I do recommend you to check your OctoberCMS Laravel version, instructions can be found [here](https://github.com/rluders/oc-cors-plugin/issues/5#issuecomment-770177860).

If you are not using the Laravel 6 version, you can update it, and the last version of both plugins should work. But I'll double test it during this weekend, and if necessary I'll release a reviewed release.

If you prefer to keep using the L5.5 version, would be better if you could get an older plugin version, from the [release page](https://github.com/rluders/oc-jwtauth-plugin/releases). I think that v1.2.3 should work fine.

I'll not support both Laravel versions, and unfortunately, by the OctoberCMS marketplace, you cannot choose the version that you want to install, as well it doesn't install the version compatible with your Laravel version. Sorry about it.

And that is it. I'll mark this issue as *wontfix* and keep it open till the final OctoberCMS release to L6 which should happen soon.
