### ISSUE TITLE
How to deal with Axios async ?

### ISSUE THREAD

**Issue by Incremental92** [rluders/oc-jwtauth-plugin#55]
I'd like to refresh the token to check it's validity, before changing the user profile or password.
The problem is that the refresh response arrives after the profile update axios call.
What could you advice to wait the new token and insure the user access is still valid ?
Thanks for your help.

**Comment by Incremental92** [comment]
A solution here : https://forum.quasar-framework.org/topic/7611/how-to-serialize-axios-functions

**Comment by rluders** [comment]
I'll assume that you already figured it out. So, I'm closing this one. Feel free to reopen if you think it is necessary.
