### ISSUE TITLE
Target class [Fruitcake\Cors\HandleCors] does not exist.

### ISSUE THREAD

**Issue by nemerki** [rluders/oc-jwtauth-plugin#57]
Hi,

I am using postmen an return this error

Target class [Fruitcake\Cors\HandleCors] does not exist.
/Applications/MAMP/htdocs/backend/E/eco/vendor/laravel/framework/src/Illuminate/Container/Container.php line 805
https://prnt.sc/y4bz2x

**Comment by rluders** [comment]
Closing it, since it is not related to this plugin.

Please, check this issue: https://github.com/rluders/oc-cors-plugin/issues/5
